### ISSUE TITLE
Latest release of (dotlottieLoader-ios 0.2.1) broke (dotLottie 0.1.9)

### ISSUE THREAD

**Issue by fmasutti** [dotlottie/dotlottieLoader-ios#6]
My Project that use the "[dotLottie](https://github.com/dotlottie/dotlottie-ios)" isn't working anymore after the latest release of "dotLottieLoader" (v 0.2.1).

Not sure exactly if is there anything that I can do on my end to fix it TBH, I did try manually add the old version of dotLottierLoader into my SwiftPackageManager but the dependency is still there into the original "dotLottie" and at end my package has 2 version of the "dotLottieLoader".

About my Environment:
Current Packages that I'm using into my SwiftPackageManger from Lottie are: 
"Lottie"     Exact Version: 3.3.0 
"doLottie" Exact Version 0.1.9.
Building Using latest Xcode: 15.1.
MacbookAir M2.

This is the error that I have locally:
![image](https://github.com/dotlottie/dotlottieLoader-ios/assets/3879882/a1aa7ee4-5885-4038-8e88-2bfda03e5524)

Created the same issue in the other repo, go ahead and close the one that isn't the right one to move forward with a fix.

**Comment by eharrison** [comment]
Hello @fmasutti, thank you for your message and I'm sorry you're having this issue.

The update was made due to the changes in Lottie-ios framework, that since 4.0.0 brings the possibility to load .lottie files directly from the framework.

Please update to the latest version 4.3.4, you will have to migrate the old AnimationView to LottieAnimationView, and Animation to LottieAnimation, but you'll have the dotLottieLoader available inside.

Once you update to the latest lottie-ios version you'll get the following methods:

![image](https://github.com/dotlottie/dotlottieLoader-ios/assets/1723967/ea436a27-3ca1-48f2-b56f-fecf63963ed0)

**Comment by fmasutti** [comment]
Closing the issue. as that shall get my problem sorted. shall give it a go next week. thanks!
